# Makefile for callgraph generation

# OS := $(shell uname)
# CG := tools/callgraph

# f: function
# d: directory or file
# b: callgraph picture displayer

ifeq ($(f),)
        f = main
endif
ifeq ($(d),)
        d = ./
endif

ifeq ($(b),)
    # Mac OS X
    ifeq ($(OS), Darwin)
        b = /Applications/Safari.app/Contents/MacOS/Safari
    else
        b = chromium-browser
    endif
endif

cg:
	@$(CG) -f $(f) -d $(d) -b $(b)

